ALTER TABLE content_records ADD COLUMN IF NOT EXISTS media_ipfs_url TEXT NOT NULL DEFAULT '';
ALTER TABLE content_records ADD COLUMN IF NOT EXISTS media_s3_url TEXT NOT NULL DEFAULT '';
ALTER TABLE content_records ADD COLUMN IF NOT EXISTS allow_ai_training BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE content_records ADD COLUMN IF NOT EXISTS media_type VARCHAR(20) NOT NULL DEFAULT 'image';
